version: '3.8'

services:
  # Service Spring Boot
  java:
    image: nejmaoui/backendpfe:pfe
    container_name: java
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Expose le port 8082 sur le port 8082 de l'hôte
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:pfe@mongodb:27017/agiledb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - my-network

  # Service MongoDB
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks:
      - my-network

  # Service Angular Frontend
  angular-frontend:
    image: nejmaoui/frontend:angular
    container_name: angular-frontend
    ports:
      - "80:80"  # Exposer l'application sur le port 80
    networks:
      - front-network
    depends_on:
      - java

# Volumes
volumes:
  mongodb_data:

# Réseaux
networks:
  my-network:
    driver: bridge
  front-network:
    driver: bridge

