# Server configuration
server.port=8082
spring.application.name=demo

# MongoDB configuration
spring.data.mongodb.uri=mongodb://admin@gmail.com:admin@localhost:27018/agiledb

spring.mongodb.embedded.version=4.0.2

# JWT configuration
jwt.secret=secret
jwt.jwtExpirationMs=86400000

# File upload size limit
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dpckairos@gmail.com
spring.mail.password=qogrnqclmbfchjlh
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.auth=true

# Circular reference handling
spring.main.allow-circular-references=true

# MySQL DataSource configuration 
spring.datasource.url=jdbc:mysql://mysql:3306/pfe?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=pfe
spring.datasource.password=pfe
